const $=s=>document.querySelector(s);
const state={unit:'celsius',place:null,weather:null,language:'auto',recognition:null,speaking:false,map:null,markers:[],routeLayer:null,from:null,to:null};
const icons={0:['☀️','Clear sky'],1:['🌤️','Mainly clear'],2:['⛅','Partly cloudy'],3:['☁️','Overcast'],45:['🌫️','Fog'],48:['🌫️','Rime fog'],51:['🌦️','Light drizzle'],53:['🌦️','Drizzle'],55:['🌧️','Heavy drizzle'],56:['🌧️','Freezing drizzle'],57:['🌧️','Heavy freezing drizzle'],61:['🌦️','Light rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],66:['🌧️','Freezing rain'],67:['🌧️','Heavy freezing rain'],71:['🌨️','Light snow'],73:['❄️','Snow'],75:['❄️','Heavy snow'],77:['❄️','Snow grains'],80:['🌦️','Rain showers'],81:['🌧️','Rain showers'],82:['⛈️','Heavy showers'],85:['🌨️','Snow showers'],86:['🌨️','Heavy snow showers'],95:['⛈️','Thunderstorm'],96:['⛈️','Thunderstorm + hail'],99:['⛈️','Thunderstorm + hail']};
const speechLocales={en:'en-IN',ta:'ta-IN',hi:'hi-IN',te:'te-IN',ml:'ml-IN',kn:'kn-IN',bn:'bn-IN',mr:'mr-IN',gu:'gu-IN',pa:'pa-IN',ar:'ar-SA',es:'es-ES',fr:'fr-FR',de:'de-DE',pt:'pt-BR',it:'it-IT',ja:'ja-JP',ko:'ko-KR',zh:'zh-CN'};
function setStatus(t,e=false){$('#status').textContent=t;$('#status').classList.toggle('error',e)}
function setAiStatus(t,e=false){$('#aiStatus').textContent=t;$('#aiStatus').classList.toggle('error',e)}
function fmtTemp(c){return state.unit==='celsius'?Math.round(c):Math.round(c*9/5+32)} function tempUnit(){return state.unit==='celsius'?'°C':'°F'}
function windValue(k){return state.unit==='celsius'?`${Math.round(k)} km/h`:`${Math.round(k*.621371)} mph`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function placeLabel(p){return [p.name,p.admin1&&p.admin1!==p.name?p.admin1:null,p.country&&p.country!==p.name?p.country:null].filter(Boolean).join(', ')}
function locale(){const v=$('#languageSelect').value;return v==='auto'?(navigator.language||'en-US'):(speechLocales[v]||v)}
function langCode(){return locale().split('-')[0]}
function dateText(tz){return new Intl.DateTimeFormat(locale(),{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:tz}).format(new Date())}
function timeText(tz){return new Intl.DateTimeFormat(locale(),{hour:'numeric',minute:'2-digit',second:'2-digit',hour12:true,timeZone:tz}).format(new Date())}
function initMap(){state.map=L.map('map',{zoomControl:true}).setView([20,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(state.map)}
function clearMarkers(){state.markers.forEach(m=>state.map.removeLayer(m));state.markers=[]}
function marker(p,title){const m=L.marker([p.latitude,p.longitude]).addTo(state.map).bindPopup(`<strong>${esc(title||placeLabel(p))}</strong>`);state.markers.push(m);return m}
async function geocode(name,language=langCode()) {const u=`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=100&language=${encodeURIComponent(language)}&format=json`;const r=await fetch(u);if(!r.ok)throw Error('Location search failed.');const d=await r.json();if(!d.results?.length)throw Error('No matching location found.');return d.results}
function renderLocationResults(results,target='cityInput'){const box=target==='cityInput'?$('#locationResults'):null;if(!box)return;box.innerHTML=results.slice(0,20).map((p,i)=>`<button type="button" class="location-option" data-index="${i}"><strong>${esc(placeLabel(p))}</strong><small>${esc([p.feature_code,p.admin2,p.country_code].filter(Boolean).join(' · '))}</small></button>`).join('');box.hidden=!results.length;box.querySelectorAll('button').forEach(b=>b.onclick=()=>selectLocation(results[+b.dataset.index]))}
function hideResults(){$('#locationResults').hidden=true;$('#locationResults').innerHTML=''}
async function fetchWeather(lat,lon){const p=new URLSearchParams({latitude:lat,longitude:lon,timezone:'auto',forecast_days:'7',current:'temperature_2m,relative_humidity_2m,apparent_temperature,precipitation,weather_code,wind_speed_10m,surface_pressure,visibility',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,sunrise,sunset'});const r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}`);if(!r.ok)throw Error('Weather service unavailable.');return r.json()}
function renderPlaceInfo(p,w){$('#placeInfo').innerHTML=`<strong>${esc(placeLabel(p))}</strong><br>Country: ${esc(p.country||'—')} · Region: ${esc(p.admin1||'—')}<br>Coordinates: ${Number(p.latitude).toFixed(5)}, ${Number(p.longitude).toFixed(5)}<br>Time zone: ${esc(w?.timezone||p.timezone||'—')}<br>Current local time: ${esc(timeText(w?.timezone||p.timezone||'UTC'))}`}
function render(place,data){state.place=place;state.weather=data;const c=data.current,meta=icons[c.weather_code]||['☁️','Weather'];document.body.dataset.weather=c.weather_code>=95?'storm':c.weather_code>=80?'rain':c.weather_code>=71?'snow':c.weather_code>=45?'fog':c.weather_code>=2?'cloud':'clear';$('#place').textContent=placeLabel(place);$('#placeMeta').textContent=[place.admin2,place.country_code].filter(Boolean).join(' · ');$('#localDate').textContent=dateText(data.timezone);$('#localTime').textContent=timeText(data.timezone);$('#condition').textContent=meta[1];$('#temperature').textContent=fmtTemp(c.temperature_2m);$('#feelsLike').textContent=`Feels like ${fmtTemp(c.apparent_temperature)}${tempUnit()}`;$('#weatherGlyph').textContent=meta[0];$('#humidity').textContent=`${Math.round(c.relative_humidity_2m)}%`;$('#wind').textContent=windValue(c.wind_speed_10m);$('#visibility').textContent=`${(c.visibility/1000).toFixed(1)} km`;$('#pressure').textContent=`${Math.round(c.surface_pressure)} hPa`;$('#timezoneLabel').textContent=data.timezone.replaceAll('_',' ');$('#sunrise').textContent=new Intl.DateTimeFormat(locale(),{hour:'numeric',minute:'2-digit',timeZone:data.timezone}).format(new Date(data.daily.sunrise[0]));$('#sunset').textContent=new Intl.DateTimeFormat(locale(),{hour:'numeric',minute:'2-digit',timeZone:data.timezone}).format(new Date(data.daily.sunset[0]));$('#rainChance').textContent=`${data.daily.precipitation_probability_max[0]}%`;$('#forecast').innerHTML=data.daily.time.map((d,i)=>{const m=icons[data.daily.weather_code[i]]||['☁️','Weather'];const day=i===0?'Today':new Intl.DateTimeFormat(locale(),{weekday:'short',timeZone:data.timezone}).format(new Date(d+'T12:00:00'));return `<article class="day"><small>${day}</small><div class="glyph">${m[0]}</div><div class="high">${fmtTemp(data.daily.temperature_2m_max[i])}${tempUnit()}</div><div class="low">${fmtTemp(data.daily.temperature_2m_min[i])}${tempUnit()}</div><div class="rain">${data.daily.precipitation_probability_max[i]}% rain</div></article>`}).join('');renderPlaceInfo(place,data);clearMarkers();state.map.setView([place.latitude,place.longitude],11);marker(place,'Selected place').openPopup()}
async function selectLocation(p){hideResults();try{setStatus('Loading live weather…');const w=await fetchWeather(p.latitude,p.longitude);render(p,w);$('#cityInput').value=placeLabel(p);setStatus(`Updated live weather for ${placeLabel(p)}.`)}catch(e){setStatus(e.message,true)}}
async function loadCity(name){try{setStatus('Searching worldwide locations…');const r=await geocode(name);if(r.length===1)await selectLocation(r[0]);else{renderLocationResults(r);setStatus(`${Math.min(r.length,20)} matching places found. Choose the exact place.`)}}catch(e){setStatus(e.message,true)}}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=locale();u.rate=.96;u.onstart=()=>{$('#stopVoiceBtn').disabled=false};u.onend=()=>{$('#stopVoiceBtn').disabled=true};window.speechSynthesis.speak(u)}
function showAi(t,say=true){$('#aiAnswer').textContent=t;if(say)speak(t)}
function weatherAnswer(p,w){const c=w.current,m=icons[c.weather_code]||['','Weather'];return `${placeLabel(p)}: ${fmtTemp(c.temperature_2m)}${tempUnit()}, ${m[1]}. Feels like ${fmtTemp(c.apparent_temperature)}${tempUnit()}, humidity ${Math.round(c.relative_humidity_2m)}%, wind ${windValue(c.wind_speed_10m)}. Local time is ${timeText(w.timezone)}.`}
async function answerWeather(q){const r=await geocode(q);if(r.length!==1){renderLocationResults(r);showAi(`I found multiple places for ${q}. Please choose the exact place on the screen.`);return}const p=r[0],w=await fetchWeather(p.latitude,p.longitude);render(p,w);$('#cityInput').value=placeLabel(p);showAi(weatherAnswer(p,w))}
async function resolvePlace(q){const r=await geocode(q);if(r.length===1)return r[0];renderLocationResults(r);throw Error('Multiple matching places. Please choose the exact destination.')}
async function routePlaces(from,to){const url=`https://router.project-osrm.org/route/v1/driving/${from.longitude},${from.latitude};${to.longitude},${to.latitude}?overview=full&geometries=geojson&steps=true`;const r=await fetch(url);if(!r.ok)throw Error('Routing service unavailable.');const d=await r.json();if(d.code!=='Ok'||!d.routes?.length)throw Error('No driving route found.');return d.routes[0]}
function routeText(route,to){const km=(route.distance/1000).toFixed(1),mins=Math.round(route.duration/60);return `Route to ${placeLabel(to)}: ${km} km, approximately ${mins} minutes by car.`}
async function makeRoute(fromQ,toQ,speakIt=true){try{$('#routeStatus').textContent='Finding places and route…';let from=fromQ,to=toQ;if(!from)throw Error('Choose a starting place.');if(typeof from==='string')from=await resolvePlace(from);if(typeof to==='string')to=await resolvePlace(to);const route=await routePlaces(from,to);state.from=from;state.to=to;clearMarkers();if(state.routeLayer)state.map.removeLayer(state.routeLayer);state.routeLayer=L.geoJSON(route.geometry,{style:{weight:5}}).addTo(state.map);marker(from,'From');marker(to,'Destination');state.map.fitBounds(state.routeLayer.getBounds(),{padding:[20,20]});const text=routeText(route,to);$('#distanceLabel').textContent=`${(route.distance/1000).toFixed(1)} km · ${Math.round(route.duration/60)} min`;$('#routeStatus').textContent=text;$('#placeInfo').innerHTML=`<strong>Directions</strong><br>From: ${esc(placeLabel(from))}<br>To: ${esc(placeLabel(to))}<br>${esc(text)}<br>Coordinates: ${Number(to.latitude).toFixed(5)}, ${Number(to.longitude).toFixed(5)}`;if(speakIt)showAi(text,true);else showAi(text,false)}catch(e){$('#routeStatus').textContent=e.message;setAiStatus(e.message,true)}}
function startListening(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setAiStatus('Voice input is not supported in this browser.',true);return}if(state.recognition){state.recognition.stop();return}const r=new SR();state.recognition=r;r.lang=locale();r.interimResults=false;r.maxAlternatives=5;r.onstart=()=>{setAiStatus('Listening…');$('#micBtn').classList.add('active')};r.onresult=e=>{const q=e.results[0][0].transcript.trim();if(!q){setAiStatus('I did not catch that. Please speak again.',true);return}$('#aiAnswer').textContent=`You: ${q}`;askAether(q)};r.onerror=e=>setAiStatus(`Voice input error: ${e.error}`,true);r.onend=()=>{$('#micBtn').classList.remove('active');state.recognition=null};r.start()}
async function askAether(q){setAiStatus('Aether AI is thinking…');const weather=/\b(weather|temperature|forecast|rain|raining|humidity|wind|snow|storm)\b/i.test(q)||/வானிலை|மழை|வெப்ப|मौसम|बारिश/.test(q);const time=/\b(time|clock|local time|what time)\b/i.test(q)||/நேரம்|समय/.test(q);const directions=/\b(direction|directions|route|navigate|how do i go|way to|distance to)\b/i.test(q)||/வழி|செல்வது எப்படி|दिशा/.test(q);
try{if(directions){let to=q.replace(/.*?(directions?|route|navigate|how do i go|way to|distance to)\s+(to\s+)?/i,'').trim();if(!to)throw Error('Tell me the destination.');const from=state.place||null;if(!from)throw Error('Choose your starting place first.');await makeRoute(from,to,true);setAiStatus('Directions ready.');return}if(weather){let place=q.replace(/^(what('?s| is)\s+)?(the\s+)?(weather|temperature|forecast)(\s+of|\s+in|\s+at)?\s*/i,'').trim();if(place){await answerWeather(place);setAiStatus('Weather answer ready.');return}}if(time){const p=state.place||await resolvePlace(q.replace(/.*?(time|clock|local time)\s*(in|at|of)?\s*/i,'').trim());const t=timeText(p.timezone||'UTC');showAi(`${placeLabel(p)} local time is ${t}.`);setAiStatus('Time ready.');return}
const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,language:locale(),weather:state.place&&state.weather?{place:placeLabel(state.place),current:state.weather.current}:null})});if(!r.ok)throw Error('AI backend not configured');const d=await r.json();showAi(d.answer||'I could not generate an answer.');setAiStatus('Aether AI ready.')}catch(e){setAiStatus(e.message||'Aether AI could not complete that request.',true);showAi(e.message||'Please try again.',true)}}
$('#searchForm').onsubmit=e=>{e.preventDefault();const q=$('#cityInput').value.trim();if(q)loadCity(q)};let timer;$('#cityInput').oninput=()=>{clearTimeout(timer);const q=$('#cityInput').value.trim();if(q.length<2){hideResults();return}timer=setTimeout(()=>geocode(q).then(renderLocationResults).catch(hideResults),300)};document.addEventListener('click',e=>{if(!e.target.closest('.search-box'))hideResults()});$('#unitBtn').onclick=()=>{state.unit=state.unit==='celsius'?'fahrenheit':'celsius';$('#unitBtn').textContent=state.unit==='celsius'?'°C':'°F';if(state.place&&state.weather)render(state.place,state.weather)};$('#locationBtn').onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{const w=await fetchWeather(p.coords.latitude,p.coords.longitude);const results=await geocode(`${p.coords.latitude},${p.coords.longitude}`).catch(()=>[]);const place=results[0]||{name:'My location',latitude:p.coords.latitude,longitude:p.coords.longitude,country:''};render(place,w);$('#cityInput').value=placeLabel(place);setStatus('Updated using your device location.')},()=>setStatus('Location permission was not granted.',true));$('#languageSelect').onchange=e=>{document.documentElement.lang=langCode();document.body.dataset.script=langCode();setAiStatus(`Language changed to ${e.target.options[e.target.selectedIndex].text}.`);if(state.place&&state.weather)render(state.place,state.weather)};$('#micBtn').onclick=startListening;$('#stopVoiceBtn').onclick=()=>{speechSynthesis?.cancel();state.recognition?.stop();setAiStatus('Aether AI ready.')};$('#routeBtn').onclick=()=>makeRoute($('#fromInput').value.trim()||state.place,$('#toInput').value.trim(),false);$('#useCurrentAsFrom').onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{const r=await geocode(`${p.coords.latitude},${p.coords.longitude}`);const from=r[0]||{name:'My location',latitude:p.coords.latitude,longitude:p.coords.longitude,country:''};state.from=from;$('#fromInput').value=placeLabel(from);setAiStatus('Starting point set to your location.')},()=>setAiStatus('Location permission was not granted.',true));let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true};window.addEventListener('load',()=>{initMap();loadCity('Coimbatore');setInterval(()=>{if(state.place&&state.weather)$('#localTime').textContent=timeText(state.weather.timezone)},1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
